# Generated by rust2rpm 26
%bcond_without check

Name:           system76-firmware
Version:        1.0.58
Release:        %autorelease
Summary:        System76 firmware update tool

SourceLicense:  GPL-3.0-only AND MIT AND MIT OR Apache-2.0
# FIXME: paste output of %%cargo_license_summary here
License:        GPL-3.0-only AND MIT AND MIT OR Apache-2.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://www.qubes-os.org
Source:         %{name}-%{version}.tar.gz

# EC patches
Patch1:         0001-Drop-hidapi-dependency.patch
Patch2:         0002-Drop-redox_hwio-dependency.patch

# buildchain patches
Patch200:       0200-Qubes-OS-support.patch
Patch201:       0201-Use-system-libsodium-instead-of-sodalite.patch
Patch202:       0202-Vendor-base32-crate.patch

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  xz-devel
BuildRequires:  libsodium

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -N -n system76-firmware-%{version} -p1
%patch -d ec -P1 -P2 -p1
%patch -d buildchain -P200 -P201 -P202 -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license buildchain/LICENSE
%license ec/LICENSE
%license ec/tool/LICENSE
%license ecflash/COPYRIGHT
%license ecflash/LICENSE
%license LICENSE.dependencies
%doc README.md
#%%{_bindir}/buildchain
#%%{_bindir}/ecflash
%{_bindir}/system76-firmware-cli
#%%{_bindir}/system76_ectool

%changelog
%autochangelog
